name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.3', '7.4', '8.2', '8.3']

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          XDEBUG_MODE: coverage
        with:
          version: 9.5
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text